server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/larskvn/Configuration-SmartHealt
          search-paths: Config-data
  application:
    name:
      config: config-service

